name: "Pull Request Docs Check"
on: 
- pull_request
- push

jobs:
  docs:

    strategy:
      matrix:
        python-version: [3.8]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
